### ISSUE TITLE
Please support uppercase for status.code

### ISSUE THREAD

**Issue by phatdotcom** [jshttp/statuses#22]
I think the code presentation would be prettier and cleaner if **statuses** add an option to replace `status.code['internal server error']` with `status.code['INTERNAL_SERVER_ERROR']`. Hope it update soon.

**Comment by dougwilson** [comment]
Hi @phatdotcom thank you for the suggestion. Unfortunately this API decision was made prior to my involvement and changing it to be upper case would be a needless breaking change.
