### ISSUE TITLE
status(n) returns n if n is a number

### ISSUE THREAD

**Issue by MiniGod** [jshttp/statuses#8]
The readme states
```javascript
status(403) // => 'Forbidden'
status('403') // => 'Forbidden'
```

But true output is
```javascript
status(403) // => 403
status('403') // => 403
```

**Comment by jonathanong** [comment]
not sure what is expected behavior. under the hood, all it's doing is:

```js
status[403] // => 403
status['403'] // => 403
```

**Comment by MiniGod** [comment]
No, it does not. Look at [lines 41-44 in index.js](https://github.com/jshttp/statuses/blob/master/index.js#L41-L44)
It checks if `status[code]` is truly, and then returns `code`.

**Comment by MiniGod** [comment]
I would expect it to return `status[code]` instead of just `code`.

**Comment by jonathanong** [comment]
ah ok. read the issue wrong. i swear your issue stated that `status(403)` and `status('403')` returned different output before.

**Comment by dougwilson** [comment]
The description above the examples asserted the same as the code: the return value is the code. In this case, the examples were just incorrect.

I think it may make sense to have a function that takes the number and returns the name so you don't have to use the exported map, though.
